### ISSUE TITLE
Is STM32L0 (especially L011) fully supported?

### ISSUE THREAD

**Issue by Riconec** [libopencm3/libopencm3#1034]
Sorry for creating an issue on such kind of question.

I am planning to use libopencm3 for small project with stm32l011 but can't find is it supported fully? (all peripherals)
I can find year or two old information about issues in L0-series support, but what is the actual status?

**Comment by karlp** [comment]
it's supported. not as well as some other parts, but well enough, and the peripherals are all the ~same so even if a peripheral isn't, it's probably just because it hasne't been tested.  http://libopencm3.org/docs/latest/stm32l0/html/modules.html has the latest documentation, and you can look at the makefile for the target to see what modules are currently compiled in.  And yes, this is not a very good issue :)
