### ISSUE TITLE
Why is dac_cr just redefined DAC_BASE ? 

### ISSUE THREAD

**Issue by W-M-D** [libopencm3/libopencm3#1188]
I just really want to know. 

#define DAC_CR				MMIO32(DAC_BASE + 0x00)

**Comment by karlp** [comment]
Because it's the first register?  I mean, you could use DAC_CR instead of DAC_BASE everywhere, but it seems much less legible.  This is how all the registers are defined, not just the DAC.

As a library _user_ you generally never see the xxx_BASE. you just use xxx_<REG_NAME>  and then just xxx for the peripheral id.  Whether a given register is at offset 0 or 10, or 300 doesn't matter.

Feel free to reopen this if that's not clear.
