### ISSUE TITLE
No interface exists to change the GCCFG register. 

### ISSUE THREAD

**Issue by rewolff** [libopencm3/libopencm3#213]
I have to enable the NOVBUSSENS bit in the GCCFG register, or maybe disable the VBUSBSEN bit. When I couldn't find a function to change the register, I tried directly changing the register, but the appropriate internal includes are not normally included... (e.g. in the libopencm3 examples cdcacm example).

**Comment by karlp** [comment]
I believe the latter issue has been fixed, via "OTG_HS_GCCFG |= OTG_GCCFG_VBUSBSEN" (which probably didn't exist when this bug was filed) and I believe, but can't find right now, that there are other issues for fiddling with vbus sensing.  They were internal, but are no longer internal includes (as they had no right to be internal only)
