### ISSUE TITLE
Compatibility with LLVM / clang

### ISSUE THREAD

**Issue by BuFran** [libopencm3/libopencm3#244]
LLVM is another compiler, that is currently on the market. BSD Unix is completely built with LLVM. It features full support of all C standards (including the 2014 one)

LLVM compiler has same arguments as GCC, so the compatibility can be easy.

LLVM supports cross-compiling for ARM since last year.

The compatibility with LLVM can be archieved by modifying some macros (CC ...)

**Comment by lukas2511** [comment]
llvm/clang compatibility would be really great, has there been any more work on this?

**Comment by karlp** [comment]
not that I'm aware of.

**Comment by Danukeru** [comment]
I can confirm that his patches are still required in order to compile and link with LLVM-4.0 which now includes lld, the new llvm linker. Using only toolchain on debian testing installed from http://apt.llvm.org/ along with g++-multilib installed.

However any naked attributes in these files must also be removed:
    include/libopencm3/cm3/scb.h
    lib/cm3/scb.c
    lib/cm3/vector.c

I left in the noreturn attributes in scb.h 

Managed to then compile and link blackmagic probe as well on same llvm only toolchain.

**Comment by karlp** [comment]
@Danukeru could you clarify please which patches you're talking about?  Do you have this in a branch of yours that could be submitted as a Pull Request for us?

**Comment by karlp** [comment]
with f53e12d2 and 8071c6cf merged, I don't know of any _outstanding_ clang/llvm requirements.

You currently need to use 
```
CC = clang -target $(PREFIX)
and
CFLAGS += --sysroot=somewhere
```

and then it all works fine.  On my fedora system, I pacakge installed arm-none-eabi-newlib and then just passed sysroot=/lib/$(PREFIX)

We cna have followup tickets for doing more with clang, but I think this one has served it's purpose.
