### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by beriberikix** [libopencm3/libopencm3#759]
Has the team looked at moving beyond ARM chipsets, in particular to the recently-popular ESP32? I suggest it because 1) they've because they've published most, if not all, [registers](https://espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf) and 2) they support GCC.

**Comment by karlp** [comment]
not particularly, largely because it becomes a whole new compiler toolchain.  Even if it's gcc, it's still a completely different set of tools.  I think esp32 (and esp8266, also with a gcc based toolchain) are very interesting, but I think it would be fairly out of scope to try and merge them into this project.  There's definitely room for higher level projects that provide cross target API compatibility for instance, but that's already being targetted by mbed/arduino et al.
